/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author 60135
 */
public class NewJFrame extends javax.swing.JFrame {
    
    private JLabel label1;
    private JLabel label2;
    private JTextField textField1;
    private JButton plainButton;
    private JButton fancyButton;
    private JTextArea Textbox1;
    private JRadioButton b1, b2, b3;
    private JComboBox ComboBox;
    private JCheckBox cb1, cb2 ;


    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        super("testing JLabel");
        Container container = getContentPane();
        container.setLayout(new FlowLayout());
        label1 = new JLabel("Label with text");
        container.add(label1);
        
        Icon rabbit = new ImageIcon("C:\\Users\\60135\\Downloads\\photo_2023-09-25_11-50-27.png");
        label2 = new JLabel("Label with text and icon", rabbit,SwingConstants.CENTER);
        label2.setToolTipText("This is an animated rabbit");
        label2.setLocation(100,200);
        container.add(label2);
        
        plainButton = new JButton("Plain Button");
        container.add(plainButton);

        Icon bug1 = new ImageIcon("C:\\Users\\60135\\Downloads\\download.png");
        fancyButton = new JButton("Fancy Button", bug1);
        container.add(fancyButton);

        textField1 = new JTextField(10);
        container.add(textField1);
        
        Textbox1 = new JTextArea ("Multiple line");
        Textbox1.setSize(100,200);
        Textbox1.setLocation(20,20);
        Textbox1.setBackground(Color.PINK);
        Textbox1.setForeground(Color.DARK_GRAY);
        Textbox1.setFont(new
        Font("Bookman",Font.TRUETYPE_FONT,16));
        add(Textbox1);
        
        ButtonGroup group1 = new ButtonGroup();
        b1 = new JRadioButton("Hagen Dazz");
        b2 = new JRadioButton("Basken Robin");
        b3 = new JRadioButton("Walls");
        b1.setBounds(20,20,200,50);
        b2.setBounds(20,70,200,50);
        b3.setBounds(20,110,200,50);
        container.add(b1);
        container.add(b2);
        container.add(b3);

        String names[]= {"kuih.gif","kuih1.gif","kuih3.gif"};
        ComboBox = new JComboBox(names);
        ComboBox.setMaximumRowCount(3);
        ComboBox.setBounds(50,50,100,20);
        add(ComboBox);

        cb1 = new JCheckBox("C");
        cb2 = new JCheckBox("JAVA");
        cb1.setBounds(20,20,200,50);
        cb2.setBounds(20,70,200,50);
        add(cb1);
        add(cb2);

        setSize(100,100);
        setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        NewJFrame application = new NewJFrame();
        application.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
